// Where each Grand Prix was held. The lap data has race names but no circuit, and a few
// names moved between circuits (European, French, German, Japanese, Portuguese, United States),
// so each name lists its circuits with the seasons they were used, 1996–2024.

export const CIRCUITS = {
  albert_park: { name: "Albert Park", city: "Melbourne", country: "Australia", lat: -37.8497, lon: 144.968 },
  americas: { name: "Circuit of the Americas", city: "Austin", country: "USA", lat: 30.1328, lon: -97.6411 },
  bahrain: { name: "Bahrain International Circuit", city: "Sakhir", country: "Bahrain", lat: 26.0325, lon: 50.5106 },
  baku: { name: "Baku City Circuit", city: "Baku", country: "Azerbaijan", lat: 40.3725, lon: 49.8533 },
  buddh: { name: "Buddh International Circuit", city: "Greater Noida", country: "India", lat: 28.3487, lon: 77.5331 },
  buenos_aires: { name: "Autódromo Oscar Gálvez", city: "Buenos Aires", country: "Argentina", lat: -34.6943, lon: -58.4593 },
  catalunya: { name: "Circuit de Barcelona-Catalunya", city: "Montmeló", country: "Spain", lat: 41.57, lon: 2.2611 },
  estoril: { name: "Autódromo do Estoril", city: "Estoril", country: "Portugal", lat: 38.7506, lon: -9.3942 },
  fuji: { name: "Fuji Speedway", city: "Oyama", country: "Japan", lat: 35.3717, lon: 138.927 },
  hockenheim: { name: "Hockenheimring", city: "Hockenheim", country: "Germany", lat: 49.3278, lon: 8.5656 },
  hungaroring: { name: "Hungaroring", city: "Budapest", country: "Hungary", lat: 47.5789, lon: 19.2486 },
  imola: { name: "Imola", city: "Imola", country: "Italy", lat: 44.3439, lon: 11.7167 },
  indianapolis: { name: "Indianapolis Motor Speedway", city: "Indianapolis", country: "USA", lat: 39.795, lon: -86.2347 },
  interlagos: { name: "Interlagos", city: "São Paulo", country: "Brazil", lat: -23.7036, lon: -46.6997 },
  istanbul: { name: "Istanbul Park", city: "Istanbul", country: "Turkey", lat: 40.9517, lon: 29.405 },
  jeddah: { name: "Jeddah Corniche Circuit", city: "Jeddah", country: "Saudi Arabia", lat: 21.6319, lon: 39.1044 },
  jerez: { name: "Circuito de Jerez", city: "Jerez", country: "Spain", lat: 36.7083, lon: -6.0342 },
  losail: { name: "Losail International Circuit", city: "Lusail", country: "Qatar", lat: 25.49, lon: 51.4542 },
  magny_cours: { name: "Magny-Cours", city: "Magny-Cours", country: "France", lat: 46.8642, lon: 3.1633 },
  marina_bay: { name: "Marina Bay Street Circuit", city: "Singapore", country: "Singapore", lat: 1.2914, lon: 103.864 },
  mexico_city: { name: "Autódromo Hermanos Rodríguez", city: "Mexico City", country: "Mexico", lat: 19.4042, lon: -99.0907 },
  miami: { name: "Miami International Autodrome", city: "Miami", country: "USA", lat: 25.9581, lon: -80.2389 },
  monaco: { name: "Circuit de Monaco", city: "Monte Carlo", country: "Monaco", lat: 43.7347, lon: 7.4206 },
  montreal: { name: "Circuit Gilles Villeneuve", city: "Montréal", country: "Canada", lat: 45.5, lon: -73.5228 },
  monza: { name: "Monza", city: "Monza", country: "Italy", lat: 45.6156, lon: 9.2811 },
  mugello: { name: "Mugello", city: "Scarperia", country: "Italy", lat: 43.9975, lon: 11.3719 },
  nurburgring: { name: "Nürburgring", city: "Nürburg", country: "Germany", lat: 50.3356, lon: 6.9475 },
  paul_ricard: { name: "Circuit Paul Ricard", city: "Le Castellet", country: "France", lat: 43.2506, lon: 5.7917 },
  portimao: { name: "Algarve International Circuit", city: "Portimão", country: "Portugal", lat: 37.227, lon: -8.6267 },
  red_bull_ring: { name: "Red Bull Ring (A1-Ring)", city: "Spielberg", country: "Austria", lat: 47.2197, lon: 14.7647 },
  sepang: { name: "Sepang International Circuit", city: "Kuala Lumpur", country: "Malaysia", lat: 2.7608, lon: 101.738 },
  shanghai: { name: "Shanghai International Circuit", city: "Shanghai", country: "China", lat: 31.3389, lon: 121.22 },
  silverstone: { name: "Silverstone", city: "Silverstone", country: "UK", lat: 52.0786, lon: -1.0169 },
  sochi: { name: "Sochi Autodrom", city: "Sochi", country: "Russia", lat: 43.4057, lon: 39.9578 },
  spa: { name: "Spa-Francorchamps", city: "Stavelot", country: "Belgium", lat: 50.4372, lon: 5.9714 },
  suzuka: { name: "Suzuka", city: "Suzuka", country: "Japan", lat: 34.8431, lon: 136.541 },
  vegas: { name: "Las Vegas Strip Circuit", city: "Las Vegas", country: "USA", lat: 36.1147, lon: -115.173 },
  valencia: { name: "Valencia Street Circuit", city: "Valencia", country: "Spain", lat: 39.4589, lon: -0.3317 },
  yas_marina: { name: "Yas Marina", city: "Abu Dhabi", country: "UAE", lat: 24.4672, lon: 54.6031 },
  yeongam: { name: "Korea International Circuit", city: "Yeongam", country: "South Korea", lat: 34.7333, lon: 126.417 },
  zandvoort: { name: "Zandvoort", city: "Zandvoort", country: "Netherlands", lat: 52.3888, lon: 4.5409 },
};

// Grand Prix name -> [circuit, first season, last season]; one entry covers every season if no years.
const HOSTS = {
  "70th Anniversary Grand Prix": [["silverstone"]],
  "Abu Dhabi Grand Prix": [["yas_marina"]],
  "Argentine Grand Prix": [["buenos_aires"]],
  "Australian Grand Prix": [["albert_park"]],
  "Austrian Grand Prix": [["red_bull_ring"]],
  "Azerbaijan Grand Prix": [["baku"]],
  "Bahrain Grand Prix": [["bahrain"]],
  "Belgian Grand Prix": [["spa"]],
  "Brazilian Grand Prix": [["interlagos"]],
  "British Grand Prix": [["silverstone"]],
  "Canadian Grand Prix": [["montreal"]],
  "Chinese Grand Prix": [["shanghai"]],
  "Dutch Grand Prix": [["zandvoort"]],
  "Eifel Grand Prix": [["nurburgring"]],
  "Emilia Romagna Grand Prix": [["imola"]],
  "European Grand Prix": [["nurburgring", 1996, 1996], ["jerez", 1997, 1997], ["nurburgring", 1999, 2007],
    ["valencia", 2008, 2012], ["baku", 2016, 2016]],
  "French Grand Prix": [["magny_cours", 1996, 2008], ["paul_ricard", 2018, 2022]],
  "German Grand Prix": [["hockenheim", 1996, 2008], ["nurburgring", 2009, 2009], ["hockenheim", 2010, 2010],
    ["nurburgring", 2011, 2011], ["hockenheim", 2012, 2012], ["nurburgring", 2013, 2013], ["hockenheim", 2014, 2019]],
  "Hungarian Grand Prix": [["hungaroring"]],
  "Indian Grand Prix": [["buddh"]],
  "Italian Grand Prix": [["monza"]],
  "Japanese Grand Prix": [["suzuka", 1996, 2006], ["fuji", 2007, 2008], ["suzuka", 2009, 2024]],
  "Korean Grand Prix": [["yeongam"]],
  "Las Vegas Grand Prix": [["vegas"]],
  "Luxembourg Grand Prix": [["nurburgring"]],
  "Malaysian Grand Prix": [["sepang"]],
  "Mexican Grand Prix": [["mexico_city"]],
  "Mexico City Grand Prix": [["mexico_city"]],
  "Miami Grand Prix": [["miami"]],
  "Monaco Grand Prix": [["monaco"]],
  "Portuguese Grand Prix": [["estoril", 1996, 1996], ["portimao", 2020, 2021]],
  "Qatar Grand Prix": [["losail"]],
  "Russian Grand Prix": [["sochi"]],
  "Sakhir Grand Prix": [["bahrain"]],
  "San Marino Grand Prix": [["imola"]],
  "Saudi Arabian Grand Prix": [["jeddah"]],
  "Singapore Grand Prix": [["marina_bay"]],
  "Spanish Grand Prix": [["catalunya"]],
  "Styrian Grand Prix": [["red_bull_ring"]],
  "São Paulo Grand Prix": [["interlagos"]],
  "Turkish Grand Prix": [["istanbul"]],
  "Tuscan Grand Prix": [["mugello"]],
  "United States Grand Prix": [["indianapolis", 2000, 2007], ["americas", 2012, 2024]],
};

// Circuit id for a race name in a season, or null if unknown.
export function circuitFor(race, year) {
  const hosts = HOSTS[race];
  if (!hosts) return null;
  for (const [id, from, to] of hosts) {
    if (from == null || (year >= from && year <= to)) return id;
  }
  return null;
}
